sudo: false

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
      env:
        - UPLOAD_COVERAGE=true
    - php: 7
    - php: hhvm
  allow_failures:
    - php: 5.5
    - php: hhvm

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - vendor/bin/phpunit

after_script:
  - if [[ $UPLOAD_COVERAGE == 'true' ]]; then ./vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml ; fi

notifications:
  email: false
  irc: "irc.freenode.org#phpab"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0ddf7e190c3ea82d710
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
