language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5
    - php: hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net#phpab"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d0ddf7e190c3ea82d710
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
